/**
 * 统一业务错误码
 */
export enum ErrorCode {
  // 通用
  INVALID_INPUT = 'INVALID_INPUT',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',

  // 认证
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',

  // 旅行
  TRIP_NOT_FOUND = 'TRIP_NOT_FOUND',
  INVALID_TRIP_WINDOW = 'INVALID_TRIP_WINDOW',
  TRIP_VERSION_CONFLICT = 'TRIP_VERSION_CONFLICT',

  // 行程
  ITEM_NOT_FOUND = 'ITEM_NOT_FOUND',
  ITINERARY_TIME_CONFLICT = 'ITINERARY_TIME_CONFLICT',

  // 报价
  QUOTE_NOT_FOUND = 'QUOTE_NOT_FOUND',
  QUOTE_EXPIRED = 'QUOTE_EXPIRED',
  QUOTE_NOT_COMPARABLE = 'QUOTE_NOT_COMPARABLE',

  // 内容
  CONTENT_NOT_FOUND = 'CONTENT_NOT_FOUND',
  CONTENT_ACCESS_NOT_AUTHORIZED = 'CONTENT_ACCESS_NOT_AUTHORIZED',

  // 地点
  PLACE_NOT_FOUND = 'PLACE_NOT_FOUND',
  PLACE_NOT_RESOLVED = 'PLACE_NOT_RESOLVED',

  // 规划
  PLAN_INFEASIBLE = 'PLAN_INFEASIBLE',
  PLAN_NOT_FOUND = 'PLAN_NOT_FOUND',

  // Provider
  PROVIDER_RATE_LIMITED = 'PROVIDER_RATE_LIMITED',
  PROVIDER_UNAVAILABLE = 'PROVIDER_UNAVAILABLE',
}
